development:
   AWS_ACCESS_KEY_ID: 'AKIA2EMSESLGBOOR36L6'
   AWS_SECRET_KEY_ID: 'DzMVvwIU9mnYuMkWHHH44iBZFvQGzlruCtyQm3cx'
   AWS_BUCKET: 'wordlconnect'
test:
   AWS_ACCESS_KEY_ID: 'AKIA2EMSESLGBOOR36L6'
   AWS_SECRET_KEY_ID: 'PDzMVvwIU9mnYuMkWHHH44iBZFvQGzlruCtyQm3cx'
   AWS_BUCKET: 'wordlconnect'
production:
   AWS_ACCESS_KEY_ID: 'AKIA2EMSESLGBOOR36L6'
   AWS_SECRET_KEY_ID: 'PDzMVvwIU9mnYuMkWHHH44iBZFvQGzlruCtyQm3cx'
   AWS_BUCKET: 'wordlconnect'